name: deploy
on:
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: docker/build-push-action@v6
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
